### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by szhan**
There is quite a bit of code that is identical across the various implementations of the LS algorithms here. This makes it cumbersome to extend the LS HMM or add new features. I think that refactoring the source code now should make it easier to maintain the code, to add new features, and to use it for prototyping extensions of the LS algorithms in the future. In this PR, I will reorganise the code, rename variables, add some documentation, do some clean up, and lint the code.

### CODE REVIEW

**Comment by szhan** [comment]
@astheeggeggs Is there a reason that the FB algorithms are organised into a separate folder? There are only two files. So, can we just flatten the folder?

**Comment by astheeggeggs** [comment]
I did have a lot more functions in with various implementations, but those have now be whittled down, so I have no objections to flattening the folder structure.

**Comment by astheeggeggs** [comment]
> There is quite a bit of code that is identical across the various implementations of the LS algorithms here. This makes it cumbersome to extend the LS HMM or add new features. I think that refactoring the source code now should make it easier to maintain the code, to add new features, and to use to for prototyping extensions of the LS algorithms in the future. In this PR, I will reorganise the code, rename variables, add some documentation, do some clean up, and lint the code.

Awesome, thanks Shing. That sounds good, as long as it's not so abstracted that it becomes trickier to understand what's going on for debugging. I'm sure you'll strike the balance!

**Comment by jeromekelleher** [comment]
LGTM!

**Comment by szhan** [comment]
@astheeggeggs @jeromekelleher I think it is now ready for review. There is a huge amount of refactoring. A lot of repeated code is now gone. All the self consistency tests pass.

**Comment by szhan** [comment]
A couple of notes to self:
* The set of tests for multiallelic sites is only covering the haploid case.
* MISSING is not being properly handled in the diploid case, which has only recently been fixed for the haploid case.

I think these can be fixed as separate issues later, once the code is refactored without changing any functionality.

**Comment by szhan** [comment]
I run black on my laptop before pushing, but it is still failing the linting stage. I suppose it has to do with differences in black configuration. I'll fix this in the next push.

**Comment by szhan** [comment]
@astheeggeggs Is there a reason that it is `n + 1` here?

https://github.com/astheeggeggs/lshmm/blob/efe28acb8d5b3ac0292656b366bd65838995d205/tests/test_LS_haploid_diploid.py#L226

**Comment by astheeggeggs** [comment]
It ensures that it won't break if you set n=1, and also that n represents the size of the reference panel.

**Comment by szhan** [comment]
Linting keeps failing on `fb_diploid.py` even though I've run black on it locally. I suspect it has to do with me screwing up when I moved the file from the directory `lshmm/forward_backward` to `lshmm/`. I moved the file, git added lshmm/fb_diploid.py, but neglected to git rm `lshmm/forward_backward/fb_diploid.py`. Ahhh, I'm not sure how to fix this.

**Comment by szhan** [comment]
Okay, I don't think I'll touch it till you will have had a chance to take a look at it. I still want to refactor it more and improve it, but most, if not all, of the major changes that I want to make are there, I think.

**Comment by jeromekelleher** [comment]
I've had a brief scan and it LGTM. I think this needs your eyes and approval @astheeggeggs.

**Comment by szhan** [comment]
A lot of the repeated code is now organised into `lshmm/core.py` and `tests/lsbase.py`.

I think the logic behind counting the number of distinct alleles and defining and accessing emission probabilities should be the same across all the LS HMM implementations. Hence, these routines are in `lshmm/core.pyt`

Also, the test data for running consistency tests should be bundled up and reused. Hence, `tests/lsbase.py`.

**Comment by szhan** [comment]
> tiny request to switch idx -> index in the Viterbi algorithm to match the forwards-backwards. Other than that, it looks good to me!

Done!

**Review by astheeggeggs — APPROVED** [review]

**Pull request merged**
