### PR TITLE
Implement NONCOPY for both the haploid and diploid cases

### LINKED ISSUE #40: Handle NONCOPY in reference panel
We want to handle `NONCOPY` states in partial ancestral haplotypes in the reference panel when running the LS Viterbi and forward-backward algorithms, for both the haploid and diploid cases.

I should have created an issue for PR #31 first. Some of the discussion has been happening there. Below is some explanation copied from PR #31.

"If ancestral haplotypes are used as part of a reference panel for LS matching, then non-copying states in them need to be treated differently than other states. When a non-copying state is encountered, the emission probability should be 0, because it is not allowed to copy from it. We arbitrarily set the numeric value of non-copying states to be -2, which is distinct from missing state that is set to -1. Here, we modify how emission probabilities are computed in the haploid version of the Viterbi algorithm. We also add examples of reference panels, queries, and expected paths for testing."

### PR DESCRIPTION
**Pull request by szhan**
Fix #40 . Replaces PR #31.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Do you want to get into the diploid side of it here?

**Comment by szhan** [comment]
> Do you want to get into the diploid side of it here?

It's taken care of now.

**Comment by szhan** [comment]
It's ready for review, I think. @astheeggeggs

**Review by astheeggeggs — APPROVED** [review]
This looks good to me!

**Comment by szhan** [comment]
is this ready for merging then? Not sure if @jeromekelleher would like to take a look too?

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by szhan** [comment]
Awesome! I'll close PR #31 but keep the discussion there.

**Pull request merged**
